### ISSUE TITLE
Weird UI with paren-face and indent-guide when region is active

### ISSUE THREAD

**Issue by ACEMerlin** [srcery-colors/srcery-emacs#3]
Without selected region (normal state):
![before](https://user-images.githubusercontent.com/5625319/50533262-3b87ce80-0b61-11e9-900d-31361e353567.png)

After select region:
![after](https://user-images.githubusercontent.com/5625319/50533266-4478a000-0b61-11e9-83f0-ab1b8c9b18a1.png)

This is what zenburn looks like with selected region
![zenburn](https://user-images.githubusercontent.com/5625319/50533293-d1235e00-0b61-11e9-96cd-aac168069365.png)

**Comment by roosta** [comment]
Not sure I understand what the problem is. Is it because the parens and indent guide gets dark like that? That's cause the face gets inverted, and unfortunately there isn't any way of forcing white foreground on inverse only so I'm not sure how to fix that. 

Alternatively you could disable inverse-video region by setting `srcery-invert-region` to nil in your init file.

**Comment by ACEMerlin** [comment]
Yes. The dark block went away after I set `srcery-invert-region` to nil.
Thanks man.

Daniel Berg <notifications@github.com> 于2018年12月29日周六 下午8:44写道：

**Comment by ACEMerlin** [comment]
Yes. The dark block went away after I set `srcery-invert-region` to nil.
Thanks man.
